### ISSUE TITLE
https://csdb.dk/rss/ doesn't work fine

### ISSUE THREAD

**Issue by Rancesk** [Reeywhaar/want-my-rss#21] opened 2019-02-04 16:24 UTC
If I open https://csdb.dk/rss/latestreleases.php I have a blank page (see the 1st attachment); in rare case it works!
Also Want-My-RSS doesn't recognise RSS links inside his RSS page. Example:
if I open https://csdb.dk/rss/ it work fine, but if then I click on a RSS link (like https://csdb.dk/rss/latestreleases.php or another link inside the RSS page) it open the RSS link like a normal site (see the 2nd attachment).
![istantanea_2019-02-04_16-59-54](https://user-images.githubusercontent.com/47328128/52221235-062d7980-28a1-11e9-97e6-c61b52aad0c6.jpg)
![istantanea_2019-02-04_17-23-30](https://user-images.githubusercontent.com/47328128/52221532-a5527100-28a1-11e9-89d0-e9c769cdf2f1.png)

**Comment by Reeywhaar** [comment] 2019-02-15 17:59
Thank you for report, definitely something wrong.

**Comment by Reeywhaar** [comment] 2019-02-15 18:37
Hmm, looks very strange, it started working right in process of debugging, and I haven't done anything :/ Now I can't reproduce the issue, but what I've found is that [line](https://github.com/Reeywhaar/want-my-rss/blob/37dae8f2032f203c00a1a751c1d5d4007482c0cb/ts/show.ts#L443) resulted in neither success, nor an error, webextension just stucked there.

**Comment by Reeywhaar** [comment] 2019-02-15 19:32
I'll be looking further, but as for now everything works. Also, you said that rss links aren't recognized on the page, but everything works for me.
![screenshot 2019-02-15 at 22 30 11](https://user-images.githubusercontent.com/884649/52879894-7aa1cb80-3171-11e9-8df8-6f67e45b25d9.png)

**Comment by Reeywhaar** [comment] 2019-02-15 19:38
Oh, it seems that I've found the issue. Request just takes a very long time to complete, so it looks like wan't my rss page get stuck as there is no loading spinner or something. For example https://csdb.dk/rss/latestcomments.php takes about 5 seconds to load for me right now.

I'm closing the issue, but if you have any thought let me know.

**Closed by Reeywhaar** 2019-02-15 19:38 UTC
